# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74273c92227b2a69b0582734583f2b2d09b72c2ddcdff5d32d226dc87938303cd8b4e27507d116e05a37232928df3a03ec795fff07b4dafb4054cb14d890ae9e

test:
  secret_key_base: 2ca80465a7b5d95f68c1719e05bccdadd939df6dbd8952df3159be4ea94f13e878bde9a598b44c24064b2f74564c37df72f48c4b3ca1be90e7e1f5ed21b315a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
